import { Update } from ".";

const P = 'party2015:';

export const UPDATES_2015: Update[] = [
  {
    date: '2015-05-01',
    rooms: {
      lake: 'archives:RoomsLake-May2015.swf'
    }
  },
  {
    date: '2015-10-21',
    temp: {
      party: {
        partyName: 'Halloween Party 2015',
        partyProgress: {
          id: 'halloween-2015',
          messageCount: 10,
          communicatorMessageCount: 5,
          taskCount: 10,
          maxCoinUpdate: 10
        },
        gameStringChanges: {
          "w.app.p2015.halloween.login1": "Gadzooks! I fear the robots I created for the 10th Anniversary Party have gone haywire! This is an especially spooky start to Halloween. Could you help me deal with these mad machines?",
          "w.app.p2015.halloween.login2": "The Gary Bot is menacing the Mine Shack right now!",
          "w.app.p2015.halloween.gary1": "Scare this robot by showing it its greatest fear: decaf coffee!",
          "w.app.p2015.halloween.gary2": "Success! That caused a fear overload. Now deactivate it.",
          "w.app.p2015.halloween.gary3": "Connect the green terminal to the yellow terminal.",
          "w.app.p2015.halloween.gary4": "Well done! We're safe from that robot, but there are others sneaking around.",
          "w.app.p2015.halloween.gary5": "Excellent work! The robot has been deactivated. Stay alert for the others.",
          "w.app.p2015.halloween.AA1": "Oh my! A robot that looks like me is scaring citizens. We have to put an end to this.",
          "w.app.p2015.halloween.AA2": "There is one thing that should stop it: my terrible spelling. Show this failed spelling test to the robot.",
          "w.app.p2015.halloween.AA3": "Excellent work! That is one less robot causing trouble.",
          "w.app.p2015.halloween.rockhopper1": "Avast! That crazy robot thinks it can be me! Head to the Forest, matey.",
          "w.app.p2015.halloween.rockhopper2": "Scare that robot with a fearsome pink flamingo!",
          "w.app.p2015.halloween.rockhopper3": "Har har! Well done, matey!",
          "w.app.p2015.halloween.Djcadence1": "Eeeeee! There's a scary robot in the Ski Village! This is a BIG one!",
          "w.app.p2015.halloween.Djcadence2": "What scares me... besides evil glitchy robots? Bugs! That's it! Show it some bugs!",
          "w.app.p2015.halloween.Djcadence3": "Whew! You did it! What a way to end the day on a high note.",
          "w.app.p2015.halloween.Dot1": "I'm all for disguises, but there's a robot that looks like me at the Cove! We have to shut it down.",
          "w.app.p2015.halloween.Dot2": "We'll have to find my greatest fear: an ugly sweater. Show one to the robot.",
          "w.app.p2015.halloween.Dot3": "Good work! That robot was no match for your scare skills!",
          "w.app.p2015.halloween.Sensei1": "There is a disturbance at the Beach. A mechanical monster wears my clothes, but not my inner calm.",
          "w.app.p2015.halloween.Sensei2": "We must scare this robot. Threaten the robot's beard with a trimmer.",
          "w.app.p2015.halloween.Sensei3": "Your beard-trimming skills are impressive! Well done, grasshopper.",
          "w.app.p2015.halloween.PH1": "Crikey! There's a rogue robot at the Snow Forts. Let's head over there!",
          "w.app.p2015.halloween.PH2": "That thing must fear whatever scares me. Show it this toy UFO.",
          "w.app.p2015.halloween.PH3": "Bonza! You took care of that robot no worries!",
          "w.app.p2015.halloween.Rookie1": "Yikes! Somebody call the EPF! The Rookie Bot is going crazy in the Plaza!",
          "w.app.p2015.halloween.Rookie2": "Ahhh!! That's scarier than a clown! Wait... that's it! Scare it with clown face paint!",
          "w.app.p2015.halloween.Rookie3": "A secret lair in the Coffee Shop? Sounds scary. I'll alert the EPF.",
          "w.app.p2015.halloween.RookieBOT1": "BZZZT! You found my fear. But you'll never find the secret lair in the Coffee Shop! ... Oops! running scared.exe! ShUTTiNG DooOOoown",
          "w.app.p2015.halloween.finale.HerbertMonologue1": "Look, I've told you before, I didn't bring Herbot back!\n\nI think it was that pesky di-",
          "w.app.p2015.halloween.finale.HerbertMonologue2": "Ah, a penguin!\nSo, you think you can just take MY inventions and turn them into party props?\nI'll show YOU not to humiliate Herbert P. Bear, Esquire!",
          "w.app.p2015.halloween.finale.HerBOTReply1": "Making the same mistakes twice, are we?\n\nI really am the superior bear.",
          "w.app.p2015.halloween.finale.HerbertScared1": "GRRRR...\n\nI knew I shouldn't have taken inspiration from that movie...",
          "w.app.p2015.halloween.finale.GaryScreen1": "Connection terminated.\n\nI'm sorry to interrupt you Herbert, if you even-",
          "w.app.p2015.halloween.finale.HerbertReply1": "WHATEVER!\n\nJust get me out of here so I can destroy you with my actual NEW inventions.",
          "w.app.p2015.halloween.finale.GaryScreen2": "Quick, we can't let Herbot escape! Credit due to Herbert, it seems as if he left the same laser intact that put Herbot out of commission the last time. Blast him with the laser and then short circuit his wires!",
          "w.app.p2015.halloween.finale.HerbertRunaway1": "MWAHAHAHAHA! You can't stop Klutzy and I!\n\nWe'll take over this whole island! Quick Klutzy, to the Skyberg!",
          "w.app.p2015.halloween.finale.GaryScreen3": "Excellent work!\nHerbert may have gotten away, but we've hopefully set him back just enough to not spoil the rest of our Halloween fun!"
        },        rooms: {

          beach: P + 'rooms/Hallo15_beach.swf',
          beacon: P + 'rooms/Hallo15_beacon.swf',
          book: P + 'rooms/Hallo15_book.swf',
          cave: P + 'rooms/Hallo15_cave.swf',
          shop: P + 'rooms/Hallo15_shop.swf',
          cloudforest: P + 'rooms/Hallo15_cloudforest.swf',
          coffee: P + 'rooms/Hallo15_coffee.swf',
          cove: P + 'rooms/Hallo15_cove.swf',
          dance: P + 'rooms/Hallo15_dance.swf',
          dock: P + 'rooms/Hallo15_dock.swf',
          dojo: P + 'rooms/Hallo15_dojo.swf',
          dojoext: P + 'rooms/Hallo15_dojoext.swf',
          agentlobbymulti: P + 'rooms/Hallo15_agentlobbymulti.swf',
          dojofire: P + 'rooms/Hallo15_dojofire.swf',
          forest: P + 'rooms/Hallo15_forest.swf',
          party1: P + 'rooms/Hallo15_party1.swf',
          party2: P + 'rooms/Hallo15_party2.swf',
          berg: P + 'rooms/Hallo15_berg.swf',
          light: P + 'rooms/Hallo15_light.swf',
          attic: P + 'rooms/Hallo15_attic.swf',
          lounge: P + 'rooms/Hallo15_lounge.swf',
          shack: P + 'rooms/Hallo15_shack.swf',
          pet: P + 'rooms/Hallo15_pet.swf',
          pizza: P + 'rooms/Hallo15_pizza.swf',
          plaza: P + 'rooms/Hallo15_plaza.swf',
          stage: P + 'rooms/Hallo15_mall.swf',
          hotellobby: P + 'rooms/Hallo15_hotellobby.swf',
          hotelroof: P + 'rooms/Hallo15_hotelroof.swf',
          hotelspa: P + 'rooms/Hallo15_hotelspa.swf',
          pufflepark: P + 'rooms/Hallo15_park.swf',
          pufflewild: P + 'rooms/Hallo15_pufflewild.swf',
          eco: P + 'rooms/Hallo15_school.swf',
          skatepark: P + 'rooms/Hallo15_skatepark.swf',
          mtn: P + 'rooms/Hallo15_mtn.swf',
          lodge: P + 'rooms/Hallo15_lodge.swf',
          village: P + 'rooms/Hallo15_village.swf',
          dojosnow: P + 'rooms/Hallo15_dojosnow.swf',
          forts: P + 'rooms/Hallo15_forts.swf',
          rink: P + 'rooms/Hallo15_rink.swf',
          town: P + 'rooms/RoomsTown-HalloweenParty2015.swf'
        },
        music: {
          beach: 1054,
          beacon: 1053,
          book: 669,
          cave: 532,
          shop: 345,
          cloudforest: 1044,
          coffee: 1031,
          cove: 1035,
          dance: 1036,
          dock: 1037,
          dojo: 403,
          dojoext: 1045,
          agentlobbymulti: 922,
          dojofire: 1046,
          forest: 1038,
          party1: 838,
          party2: 1058,
          berg: 1043,
          light: 588,
          attic: 884,
          lounge: 1055,
          shack: 1041,
          pet: 659,
          pizza: 1033,
          plaza: 1052,
          stage: 1032,
          hotellobby: 1048,
          hotelroof: 1049,
          hotelspa: 1050,
          pufflepark: 1051,
          pufflewild: 1057,
          eco: 1040,
          skatepark: 1034,
          mtn: 1042,
          lodge: 1056,
          village: 1042,
          dojosnow: 1047,
          forts: 1039,
          rink: 1067,
          town: 1052
        },
        fileChanges: {
          'play/v2/client/interface.swf': P + 'client/ClientInterface-HalloweenParty2015.swf',
          'play/v2/content/global/content/features.swf': P + 'content/ContentFeatures-HalloweenParty2015.swf',
          'play/v2/content/global/content/logo.swf': P + 'content/ContentLogo-HalloweenParty2015.swf',
          'play/v2/content/global/content/party_icon.swf': P + 'content/ContentParty_icon-HalloweenParty2015.swf',
          'play/v2/content/global/avatar/sprites/penguin_robot.swf': P + 'avatar/PenguinRobot.swf',
          'play/v2/content/global/telescope/telescope.swf': P + 'other/Telescope-HalloweenParty2015.swf',
          'play/v2/content/global/binoculars/binoculars.swf': P + 'other/Binoculars-HalloweenParty2015.swf',
          'play/v2/content/global/rooms/mall.swf': P + 'rooms/Hallo15_mall.swf',
          'play/v2/content/global/rooms/school.swf': P + 'rooms/Hallo15_school.swf',
          'play/v2/content/global/rooms/park.swf': P + 'rooms/Hallo15_park.swf',
          'play/v2/content/global/rooms/partysolo1.swf': P + 'rooms/Hallo15_partysolo1.swf',
          'play/v2/content/global/membership/party1.swf': P + 'membership/MembershipParty1-HalloweenParty2015.swf',
          'play/v2/content/global/membership/party2.swf': P + 'membership/MembershipParty2-HalloweenParty2015.swf',
          'play/v2/content/global/music/345.swf': P + 'music/Music345.swf',
          'play/v2/content/global/music/403.swf': P + 'music/Music403.swf',
          'play/v2/content/global/music/532.swf': P + 'music/Music532.swf',
          'play/v2/content/global/music/588.swf': P + 'music/Music588.swf',
          'play/v2/content/global/music/659.swf': P + 'music/Music659.swf',
          'play/v2/content/global/music/669.swf': P + 'music/Music669.swf',
          'play/v2/content/global/music/838.swf': P + 'music/Music838.swf',
          'play/v2/content/global/music/884.swf': P + 'music/Music884.swf',
          'play/v2/content/global/music/922.swf': P + 'music/Music922.swf',
          'play/v2/content/global/music/1031.swf': P + 'music/Music1031.swf',
          'play/v2/content/global/music/1032.swf': P + 'music/Music1032.swf',
          'play/v2/content/global/music/1033.swf': P + 'music/Music1033.swf',
          'play/v2/content/global/music/1034.swf': P + 'music/Music1034.swf',
          'play/v2/content/global/music/1035.swf': P + 'music/Music1035.swf',
          'play/v2/content/global/music/1036.swf': P + 'music/Music1036.swf',
          'play/v2/content/global/music/1037.swf': P + 'music/Music1037.swf',
          'play/v2/content/global/music/1038.swf': P + 'music/Music1038.swf',
          'play/v2/content/global/music/1039.swf': P + 'music/Music1039.swf',
          'play/v2/content/global/music/1040.swf': P + 'music/Music1040.swf',
          'play/v2/content/global/music/1041.swf': P + 'music/Music1041.swf',
          'play/v2/content/global/music/1042.swf': P + 'music/Music1042.swf',
          'play/v2/content/global/music/1043.swf': P + 'music/Music1043.swf',
          'play/v2/content/global/music/1044.swf': P + 'music/Music1044.swf',
          'play/v2/content/global/music/1045.swf': P + 'music/Music1045.swf',
          'play/v2/content/global/music/1046.swf': P + 'music/Music1046.swf',
          'play/v2/content/global/music/1047.swf': P + 'music/Music1047.swf',
          'play/v2/content/global/music/1048.swf': P + 'music/Music1048.swf',
          'play/v2/content/global/music/1049.swf': P + 'music/Music1049.swf',
          'play/v2/content/global/music/1050.swf': P + 'music/Music1050.swf',
          'play/v2/content/global/music/1051.swf': P + 'music/Music1051.swf',
          'play/v2/content/global/music/1052.swf': P + 'music/Music1052.swf',
          'play/v2/content/global/music/1053.swf': P + 'music/Music1053.swf',
          'play/v2/content/global/music/1054.swf': P + 'music/Music1054.swf',
          'play/v2/content/global/music/1055.swf': P + 'music/Music1055.swf',
          'play/v2/content/global/music/1056.swf': P + 'music/Music1056.swf',
          'play/v2/content/global/music/1057.swf': P + 'music/Music1057.swf',
          'play/v2/content/global/music/1058.swf': P + 'music/Music1058.swf',
          'play/v2/content/global/music/1067.swf': P + 'music/Music1067.swf'
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: P + 'close_ups/Close_upsQuest_interface-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame0.swf': { en: P + 'close_ups/Close_upsTiles_minigame0-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame1.swf': { en: P + 'close_ups/Close_upsTiles_minigame1-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame2.swf': { en: P + 'close_ups/Close_upsTiles_minigame2-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame3.swf': { en: P + 'close_ups/Close_upsTiles_minigame3-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame4.swf': { en: P + 'close_ups/Close_upsTiles_minigame4-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame5.swf': { en: P + 'close_ups/Close_upsTiles_minigame5-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame6.swf': { en: P + 'close_ups/Close_upsTiles_minigame6-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame7.swf': { en: P + 'close_ups/Close_upsTiles_minigame7-HalloweenParty2015.swf' },
          'close_ups/tiles_minigame8.swf': { en: P + 'close_ups/Close_upsTiles_minigame8-HalloweenParty2015.swf' },
          'close_ups/dialogue_login.swf': { en: P + 'close_ups/Hallo15_dialogue_login.swf' },
          'close_ups/dialogue_AA_start.swf': { en: P + 'close_ups/Hallo15_dialogue_AA_start.swf' },
          'close_ups/dialogue_AA_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_AA_instruct.swf' },
          'close_ups/dialogue_AA_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_AA_congrats.swf' },
          'close_ups/dialogue_Cad_start.swf': { en: P + 'close_ups/Hallo15_dialogue_Cad_start.swf' },
          'close_ups/dialogue_Cad_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_Cad_instruct.swf' },
          'close_ups/dialogue_Cad_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_Cad_congrats.swf' },
          'close_ups/dialogue_Dot_start.swf': { en: P + 'close_ups/Hallo15_dialogue_Dot_start.swf' },
          'close_ups/dialogue_Dot_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_Dot_instruct.swf' },
          'close_ups/dialogue_Dot_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_Dot_congrats.swf' },
          'close_ups/dialogue_PH_start.swf': { en: P + 'close_ups/Hallo15_dialogue_PH_start.swf' },
          'close_ups/dialogue_PH_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_PH_instruct.swf' },
          'close_ups/dialogue_PH_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_PH_congrats.swf' },
          'close_ups/dialogue_RH_start.swf': { en: P + 'close_ups/Hallo15_dialogue_RH_start.swf' },
          'close_ups/dialogue_RH_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_RH_instruct.swf' },
          'close_ups/dialogue_RH_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_RH_congrats.swf' },
          'close_ups/dialogue_Rook_start.swf': { en: P + 'close_ups/Hallo15_dialogue_Rook_start.swf' },
          'close_ups/dialogue_Rook_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_Rook_instruct.swf' },
          'close_ups/dialogue_Rook_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_Rook_congrats.swf' },
          'close_ups/dialogue_Rookie_bot.swf': { en: P + 'close_ups/Hallo15_dialogue_Rookie_bot.swf' },
          'close_ups/dialogue_Sen_start.swf': { en: P + 'close_ups/Hallo15_dialogue_Sen_start.swf' },
          'close_ups/dialogue_Sen_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_Sen_instruct.swf' },
          'close_ups/dialogue_Sen_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_Sen_congrats.swf' },
          'close_ups/dialogue_Gary_instruct.swf': { en: P + 'close_ups/Hallo15_dialogue_Gary_instruct.swf' },
          'close_ups/dialogue_Gary_instruct_2.swf': { en: P + 'close_ups/Hallo15_dialogue_Gary_instruct_2.swf' },
          'close_ups/dialogue_Gary_instruct_3.swf': { en: P + 'close_ups/Hallo15_dialogue_Gary_instruct_3.swf' },
          'close_ups/dialogue_Gary_lair.swf': { en: P + 'close_ups/Hallo15_dialogue_Gary_lair.swf' },
          'close_ups/dialogue_Gary_congrats.swf': { en: P + 'close_ups/Hallo15_dialogue_Gary_congrats.swf' },
          'close_ups/dialogue_Gary_final.swf': { en: P + 'close_ups/Hallo15_dialogue_Gary_final.swf' },
          'close_ups/dialogue_Herbert_caged.swf': { en: P + 'close_ups/Hallo15_dialogue_Herbert_caged.swf' },
          'close_ups/dialogue_Herbert_escape.swf': { en: P + 'close_ups/Hallo15_dialogue_Herbert_escape.swf' },
          'close_ups/dialogue_Herbot.swf': { en: P + 'close_ups/Hallo15_dialogue_Herbot.swf' },
          'close_ups/dialogue_Herbert_monologue.swf': { en: P + 'close_ups/Hallo15_dialogue_Herbert_monologue.swf' },
          'close_ups/dialogue_Herbert_monologue_2.swf': { en: P + 'close_ups/Hallo15_dialogue_Herbert_monologue_2.swf' },
          'membership/party1.swf': { en: P + 'membership/MembershipParty1-HalloweenParty2015.swf' },
          'membership/party2.swf': { en: P + 'membership/MembershipParty2-HalloweenParty2015.swf' }
        }
      }
    }
  },
  {
    date: '2015-11-04',
    end: ['party']
  }
];